### PR TITLE
Convert the project to be a gem

### PR DESCRIPTION
**Pull request by tbugai**
Change the directory structure around a little bit and add the missing bits to make it a Gem.

### CODE REVIEW

**Comment by jonathanpenn** [comment]
Looks great. Thanks!

**Comment by alloy** [comment]
Thanks, guys!

@tbugai Do you need the gem pushed to rubygems.org? (Because the gemspec isn’t fully complete yet.)

**Comment by naoyamakino** [comment]
@alloy @tbugai it would be very nice if you can make this gem publicly available. could you push this gem to rubygems?

**Comment by tbugai** [comment]
I didn't have all of the information to complete the gemspec at the time.  I personally don't believe it should be on rubygems until the library is more mature, but it should be a gem to easily pull it into projects.

**Comment by naoyamakino** [comment]
understood, I will keep using it locally then. thanks for your work!

**Pull request merged**
